spring.application.name=TestSpringApp

spring.datasource.url=jdbc:postgresql://localhost:5432/testApp
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.liquibase.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always